name: Security Analysis (Atom/CDXGen)

# Author: Robert Zheng
# created: 2026-01-12
# updated: 2026-01-12
# version: 1.0.0

# creates a docs/ folder with the SBOM and Atom slice
# commits the SBOM and Atom slice to the repository
# uploads the SBOM and Atom slice as an artifact

run-name: Security Analysis (Atom/CDXGen SBoM) by ${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Node.js v24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Tools
        run: |
          npm install -g @appthreat/atom @cyclonedx/cdxgen

      - name: Prepare Output Directory
        run: mkdir -p docs

      - name: Run Atom Analysis
        run: |
          atom -J-Xmx16g usages -o ./docs/app.atom --slice-outfile ./docs/atom_v2.1.0.json -l cpp ./src

      - name: Run CDXGen
        env:
          FETCH_LICENSE: true
        run: |
          cdxgen -o ./docs/sbom_v2.1.0.json -t cpp --usages-slices-file ./docs/atom_v2.1.0.json --author "ZHENG Robert" --version "1.0.0" --group "net.hase-zheng" --name "rw_gh-docs" --deep -r ./src

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: docs/

      - name: Commit and Push SBOM
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/sbom_v2.1.0.json docs/atom_v2.1.0.json
          git commit -m "Security: Update SBOM and Atom slice [skip ci]" || echo "No changes to commit"
          git push
